<?php

namespace YZ\EcommerceBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
  public function findCategory($limit)
  {
    $qb = $this->createQueryBuilder('c')
    ->orderBy('c.name')
    ->setMaxResults($limit);
   return $qb->getQuery()->getResult();
  }
}
