<?php

namespace YZ\EcommerceBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
  public function findLastCommande()
  {
    $qb = $this->createQueryBuilder('c')
    ->orderBy('c.id', 'DESC');
   return $qb->getQuery()->getSingleResult();
  }
}
