<?php

namespace YZ\EcommerceBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
  public function findLastCommande()
  {
    $qb = $this->createQueryBuilder('c')
    ->orderBy('c.id', 'DESC')
    ->setMaxResults( 1 );
   return $qb->getQuery()->getScalarResult();
  }
  public function findOrderByUser($id){
      $qb = $this->createQueryBuilder('c')
      ->leftJoin('c.user', 'u')
      ->addSelect('u')
      ->where('u.id = :id')
      ->setParameter('id', $id);
     return $qb->getQuery()->getResult();
  }
  public function findOrder($id){
    $qb = $this->createQueryBuilder('c')
    ->leftJoin('c.user', 'u')
    ->addSelect('u')
    ->where('c.id = :id')
    ->setParameter('id', $id);
    return $qb->getQuery()->getSingleResult();
  }
  
}
