<?php

namespace YZ\EcommerceBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
  public function findProduct($slug)
  {
    $qb = $this->createQueryBuilder('p')
    ->where('p.slug = :slug')
    ->setParameter('slug', $slug);
   return $qb->getQuery()->getSingleResult();
  }
}
