# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  yz.form.registration:
          class: YZ\UserBundle\Form\Type\RegistrationFormType
          tags:
              - { name: form.type, alias: yz_user_registration }
  twig.extension.intl:
          class: Twig_Extensions_Extension_Intl
          tags:
              - { name: twig.extension }
