# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  sonata.form.registration:
          class: Application\Sonata\UserBundle\Form\Type\RegistrationFormType
          tags:
              - { name: form.type, alias: sonata_user_registration }

  sonata.handler.registration:
          class: Application\Sonata\UserBundle\Form\Handler\RegistrationFormHandler
          arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
          scope: request
          public: false
