<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'yz_somme_tva' shared service.

return $this->services['yz_somme_tva'] = new \YZ\EcommerceBundle\Extension\SommeTva();
