<?php

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;

    /**
    * @ORM\Column(type="string", length=255)
    *
    * @Assert\NotBlank(message="Please enter your name.", groups={"Registration", "Profile"})
    * @Assert\Length(
    *     min=3,
    *     max=255,
    *     minMessage="The name is too short.",
    *     maxMessage="The name is too long."
    * )
    */
   protected $name;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }
}
