<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPhhulli\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPhhulli/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPhhulli.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPhhulli\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPhhulli\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Phhulli',
    'container.build_id' => '4a048d9d',
    'container.build_time' => 1544043509,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPhhulli');
